PhotoUploader/Controllers/PhotoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhotoUploader.Models;
using PhotoUploader.Services;

namespace PhotoUploader.Controllers
{
    [Authorize]
    public class PhotoController : Controller
    {
        private readonly IPhotoService _photoService;
        private const int _maxFiles = 10;

        public PhotoController(IPhotoService photoService)
        {
            _photoService = photoService;
        }

        [HttpGet]
        public IActionResult Index() => View();

        [HttpGet]
        public async Task<IActionResult> UploadPopup()
        {
            var photos = await _photoService.GetPhotosAsync();
            return PartialView("_UploadPopup", photos);
        }

        [HttpPost]
        [RequestSizeLimit(long.MaxValue)]
        public async Task<IActionResult> Upload(UploadPhotosModel model)
        {
            if (model.Files == null)
            {
                return PartialView("_PhotoListPartial", await _photoService.GetPhotosAsync());
            }

            var response = await _photoService.UploadPhotoAsync(new UploadPhotosModel { Files = model.Files, TagId = model.TagId }, _maxFiles);

            var photos = await _photoService.GetPhotosAsync();

            if ((response.InvalidCountFiles.Count + response.InvalidTypeFiles.Count + response.InvalidSizeFiles.Count + response.DuplicateFiles.Count) == 0)
            {
                ViewBag.Success = true;
            }
            else
            {
                ViewBag.InvalidSizeFiles = response.InvalidSizeFiles;
                ViewBag.InvalidTypeFiles = response.InvalidTypeFiles;
                ViewBag.InvalidCountFiles = response.InvalidCountFiles;
                ViewBag.FilesCount = model.Files.Count;
                ViewBag.UploadedFilesCount = response.ValidFiles.Count;
                ViewBag.DuplicateFiles = response.DuplicateFiles;
            }

            return PartialView("_PhotoListPartial", photos);
        }

        [HttpPost]
        public async Task<IActionResult> SetMain(Guid id)
        {
            // Установка выбранной фото как главной в базе данных
            await _photoService.SetMainPhotoAsync(id);

            // Обновление списка фото на странице (частичное представление)
            var photos = await _photoService.GetPhotosAsync();
            return PartialView("_PhotoListPartial", photos);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(Guid id)
        {
            // Удаление фото из базы данных и файлов с сервера
            await _photoService.DeletePhotoAsync(id);

            // Обновление списка фото на странице (частичное представление)
            var photos = await _photoService.GetPhotosAsync();
            return PartialView("_PhotoListPartial", photos);
        }

        [HttpGet]
        public async Task<IActionResult> Gallery()
        {
            var photos = await _photoService.GetPhotosAsync();
            List<string> tags = photos
                .Select(photo => photo.Tag?.Name)
                .Distinct()
                .ToList();

            if(photos.Any(p => p.Tag == null))
            {
                tags.Insert(0, "Без Тега");
            }
            
            var photosViewModel = new List<PhotoViewModel>();
            foreach(var photo in photos)
            {
                photosViewModel.Add(new PhotoViewModel
                {
                    Id = photo.Id,
                    FileName = photo.FileName,
                    UrlOriginal = photo.UrlOriginal,
                    UrlSmall = photo.UrlSmall,
                    UrlThumb = photo.UrlThumb,
                    IsMain = photo.IsMain,
                    TagName = photo.Tag == null ? "Без Тега" : photo.Tag.Name
                });
            }

            GalleryViewModel model = new GalleryViewModel
            {
                Photos = photosViewModel,
                Tags = tags
            };

            return View(model);
        }
    }
}

PhotoUploader/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhotoUploader</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PhotoUploader.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/notification.css" />
    <link rel="stylesheet" href="~/css/custom-file-input.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@fancyapps/ui@5.0/dist/fancybox/fancybox.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Photo" asp-action="Index">PhotoUploader</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Photo" asp-action="Index">Загрузка фото</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Photo" asp-action="Gallery">Галерея</a>
                        </li>
                    </ul>
                </div>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item d-flex align-items-center">
                                <span class="navbar-text" style="font-size: larger;">
                                @User.Identity.Name
                                </span>
                            </li>
                            <li class="nav-item">
                                <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" class="d-inline">
                                    <button type="submit" class="btn btn-link nav-link">Выход</button>
                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div id="notificationContainer"></div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PhotoUploader
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/notification.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>